### ISSUE TITLE
Experience Cauldron not accepting XP

### ISSUE THREAD

**Issue by Boomer-1** [NCBPFluffyBear/FlowerPower#2]
## Description (Required)

As you'll see in the video, I have 14 levels of XP. it only allows me to right click it twice to accept xp. When I started with 9 plus levels, I was able to right click 3 times and it accepted the xp. 

Also, the first click seems to require that the xp bar be at least half way full, or I can't deposit any.

## Steps to reproduce the Issue (Required)

https://youtu.be/-5wGtwBJEUo

## Expected behavior (Required)

XP to go into the cauldron

## Server Log / Error Report

no errors

## Environment (Required)

 - Minecraft Version: 1.17.1
 - CS-CoreLib Version: n/a
 - Slimefun Version: dev 961
 - Plugin Version: 3

**Comment by NCBPFluffyBear** [comment]
I'm not able to reproduce this... Could you send me a screenshot of /sf versions? I want to see your server jar and verify some of your versions. Also, can you give me an exact experience amount so I can reproduce this exactly? `/experience query <name> points` should tell you this.

**Comment by Boomer-1** [comment]
i won't have the experience #'s from the video. they've changed since then.

![image](https://user-images.githubusercontent.com/75179680/130379847-2f644362-a7ec-4f18-8b48-a0134592d2d1.png)
![image](https://user-images.githubusercontent.com/75179680/130379875-fde1256d-a6e9-45f7-9b90-9cb484fef5ee.png)
![image](https://user-images.githubusercontent.com/75179680/130379901-988b24c5-2a06-4efc-a9a3-fa2a8de381d8.png)

**Comment by Boomer-1** [comment]
not sure what the error is with customizer. just restarted the server. I'll go check it out real quick

**Comment by Boomer-1** [comment]
the slimecustomizer error is because the config has the mobdrops example drop at 0. the error said it has to be between 1-100.

**Comment by NCBPFluffyBear** [comment]
Fixed SlimeCustomizer, ty. Try updating paper, I think previous versions have some kind of experience calculation bug. When this addon was submitted for the addon jam, there was a note that some experience calculation was buggy but I was never able to reproduce it. I'm on 172, so consider that as a minimum version for now I guess.

**Comment by Boomer-1** [comment]
i updated to the latest paper and it didn't fix it. 

When i ran the experience command, i have 11 levels and 16 points.

**Comment by Boomer-1** [comment]
I've been doing some testing, and i can't find a pattern. when i first did it, i had 9 levels and a couple leftover points, and deposited all 3. with 14 levels, could only deposit twice. with 15 could do 3 times to fill it. I'm trying different amounts of points and levels and can't find a pattern yet. More often than not it works, but the 3rd fill doesn't always go in.

**Comment by NCBPFluffyBear** [comment]
I still can't get it to do that... Just to be sure, could you record yourself reproducing it again and run /sf versions in the video?

**Comment by Boomer-1** [comment]
https://youtu.be/PgbYAU5vxkY

**Comment by NCBPFluffyBear** [comment]
I decided to revisit this... but still there's no way I can reproduce this. Do you have any ideas as to why this is happening? Could you send me your server jar & plugins folder so I can test with your setup?
